// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:nex_music/core/services/hive/hive__adapter_model/hive_quality_class.dart';
import 'package:nex_music/enum/quality.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AudioQualityAdapter());
    registerAdapter(HiveQualityAdapter());
    registerAdapter(ThumbnailQualityAdapter());
  }
}
